### ISSUE TITLE
Customer group price does not update on customer group change

### ISSUE THREAD

**Issue by ioanmeri** [scandipwa/base-theme#940]
**To Reproduce**:
1. Create a Catalog Price Rule of 10% discount for **General** Customer Group
2. Login to website
3. See the As low as.. in product listing
4. Logout
5. the As low as.. still appears even the customer group in NOT LOGGED IN now

**Versions**:
base-theme v.3 stable

**Additional context**:
* Sometimes the As low as.. is showing in Product Listing but not in Product Page for logged in user. 
* The same happens if I apply Customer Group Price for one specific product via Advanced Pricing
* Issue is resolved if I navigate to some other category

Also, the same happens If I don't cache **any** (workbox) items in Cache Storage. Maybe it has to do with component level state and not service worker?

**Comment by alfredsgenkins** [comment]
It shoudl be fixed in `2.16.2` and will be released as `3.0.1`. Thanks for report!

**Comment by lion152** [comment]
"As low as" shown on all configurable products as of right now, the Catalogue price rule with discount has nothing to do with showing this label. This is a separate bug and new Issue was created for this bug https://github.com/scandipwa/base-theme/issues/1006

**Comment by lion152** [comment]
After logout/login browser cache is not flushed hence you can still see the discount which is only meant for logged in users.

**Comment by aleksandrakorolova** [comment]
Can't reproduce
I created catalog rule $10 discount for Attribute - Shoes  
https://drive.google.com/file/d/1JWvn04B5JomGTdis7XWBV9jm22HWPP9d/view?usp=sharing

Created related issue - #1727
